# local/default
endpoints:
  hypermedia:
    enabled: true

info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@maven.compiler.source@'
      target: '@maven.compiler.target@'
    project:
      name: '@project.name@'
      groupId: '@project.groupId@'
      artifactId: '@project.artifactId@'
      version: '@project.version@'

management:
  context-path: '/monitoring'
  port: 13581
  security:
    enabled: false

security:
  basic:
    enabled: false
  headers:
    # disables pragma no-cache header
    cache: false

server:
  contextPath: /
  server-header: "@project.name@ v@project.version@"

spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
    mode: HTML
    
buda:
  S3resolver: 'io.bdrc.iiif.resolver.BdrcS3Resolver'

---

# PROD
management:
  security:
    enabled: true

security:
  user:
    name: admin
    password: secret

spring:
  profiles: PROD
  thymeleaf:
    cache: true
    
buda:
  S3resolver: 'io.bdrc.iiif.resolver.BdrcS3Resolver'